---
theme:  "support-balsamiq-com"
baseurl:  "http://supportstaging.balsamiq.com"
languageCode:  "en-us"
title:  "Balsamiq Support Portal"
MetaDataFormat:  "yaml"
pluralizeListTitles:  false
Paginate:  "50"
PageSize:  "50"
contentdir:  "content"
layoutdir:  "layouts"
publishdir:  "public"
params:
  balsamiqcomurl: "http://staging.balsamiq.com"

blackfriday:
  plainIdAnchors:  true

taxonomies:
  category:  "categories"
  tag:  "tags"
  
menu.menudesktop:
  name:  "desktop"
  identifier:  "desktop"
  url:  "/desktop/"

menu.menumybalsamiq:
  name:  "mybalsamiq"
  identifier:  "mybalsamiq"
  url:  "/mybalsamiq/"

menu.menuplugins:
  name:  "plugins"
  identifier:  "plugins"
  url:  "/plugins/"

menu.menupurchasing:
  name:  "licensing and purchasing"
  identifier:  "purchasing"
  url:  "/purchasing/"

menu.menuinstallation:
  name:  "installing and updating"
  identifier:  "installation"
  url:  "/installation/"

menu.menuresources:
  name:  "resources"
  identifier:  "resources"
  url:  "/resources/"

menu.menututorials:
  name:  "tutorials"
  identifier:  "tutorials"
  url:  "/tutorials/"

---
